name: "Setup YQ Example - MacOS"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: "Version of YQ to install"
        default: "v4.35.1"
      download-compressed:
        type: boolean
        required: false
        description: "Download .tar.gz of binary rather than raw binary.  Save the tubes."
        default: true
      force:
        type: boolean
        required: false
        description: "Do not check for existing yq installation before continuing."
        default: false

jobs:
  example:
    runs-on: macos-latest
    steps:
      - name: 'Setup yq'
        uses: dcarbone/install-yq-action@v1.1.0
        with:
          version: '${{ inputs.version }}'
          download-compressed: '${{ inputs.download-compressed }}'
          force: '${{ inputs.force }}'

      - name: 'Check yq'
        run: |
          which yq
          yq --version
